name: Build and Publish Docker Image

on:
  push:
    branches: 
      - main
      - develop
      - 'develop/**'
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: 
      - main
      - develop
      - 'develop/**'

env:
  # Use docker.io for Docker Hub
  REGISTRY: docker.io
  # We will use your Docker Hub username and the app name
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/Asentinel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against Docker Hub except on PR
      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
